export const mockThrowError = async () => {
  throw new Error();
};
